"""Reset e criação inicial das tabelas

Revision ID: 091bc7ece679
Revises: 
Create Date: 2026-01-31 01:12:37.522590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091bc7ece679'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('cellphone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tax_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('party_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('shareable_link_id', sa.String(length=16), nullable=False),
    sa.Column('public_description', sa.Text(), nullable=True),
    sa.Column('show_guest_count', sa.Boolean(), nullable=False),
    sa.Column('share_code', sa.String(length=8), nullable=False),
    sa.Column('ticket_price', sa.Float(), nullable=False),
    sa.Column('allow_public_purchase', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.Time(), nullable=True),
    sa.Column('invite_font', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_code'),
    sa.UniqueConstraint('share_code'),
    sa.UniqueConstraint('shareable_link_id')
    )
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('qr_hash', sa.String(length=64), nullable=False),
    sa.Column('entered', sa.Boolean(), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payment_charge_id', sa.String(length=120), nullable=True),
    sa.Column('pix_qr_code_filename', sa.String(length=255), nullable=True),
    sa.Column('pix_emv_code', sa.Text(), nullable=True),
    sa.Column('pix_created_at', sa.DateTime(), nullable=True),
    sa.Column('purchase_link_id', sa.String(length=64), nullable=True),
    sa.Column('purchased_by_user_id', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['purchased_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_charge_id'),
    sa.UniqueConstraint('purchase_link_id'),
    sa.UniqueConstraint('qr_hash')
    )
    op.create_table('party_collaborators',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'party_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('party_collaborators')
    op.drop_table('guest')
    op.drop_table('party')
    op.drop_table('user')
    # ### end Alembic commands ###
